### ISSUE TITLE
Some errors in the js?

### ISSUE THREAD

**Issue by nichthinkof30** [bassjobsen/wysihtml5-image-upload#2]
I'm using ROR, and when I load all the compiled assets and load the page. There is an error 'Cannot read property 'Constructor' of undefined', I found out the error is come from custom_image_and_upload_wysihtml5.js...anyway to correct it?

**Comment by bassjobsen** [comment]
Hi,

Thanks for your message. Does this link help you futher? http://stackoverflow.com/questions/14121509/error-uncaught-typeerror-cannot-read-property-constructor-of-undefined-boots
