### ISSUE TITLE
ReferenceError: caption is not defined

### ISSUE THREAD

**Issue by teakay** [bassjobsen/wysihtml5-image-upload#3]
Hi,

I tried to install this plugin into Codeigniter and having errors on underscore-min.js
said  : ReferenceError: caption is not defined

But I found there's no problem using it in plain structural php or html.

Any help I really appreciate.
Thx

**Comment by bassjobsen** [comment]
Hi,

The handler for the imagelist (imagelist.php in this example) code requires two fields `file` and `caption`. The json encode output should be at least:
`[{"file":"http://placehold.it/50/B9E4FB/260b50","caption":"This image...#260b50"}]`

If you don't have a caption field for some reason, you should have to change the template. You will find this template in js/custom_image_and_upload_wysihtml5.js line 27:

`var optionTemplate = _.template(
      "<tr><td class='row' data-type='image' data-caption='<%= caption %>' data-url='<%= file %>'>" +
        "<img class='span1' src='<%= file %>' width='50'>"+
        "<div class='span4 caption'><%= caption %></div>" + 
        "</td></tr>");`
