### ISSUE TITLE
error when placed on ajax form

### ISSUE THREAD

**Issue by achmadtunggulaji** [bassjobsen/wysihtml5-image-upload#4]
when use default post form without ajax everything work okay, but when i switch it to form with ajax post upload url for wysihtml5-image-upload pointed to form ajax not to wysihtml5-image-upload url, how to fix it?

by the way, thanks for making this script

**Comment by bassjobsen** [comment]
Thanks. Please see the explanation on https://github.com/bassjobsen/wysihtml5-image-upload at "upload.php" if you change the file name you also will have to change it in custom_image_and_upload_wysihtml5.js.
You form could post to an other url (wysihtml5-image-upload uploads the image to the server and create a link to it in the text area, the content of this texterea will submit with your form ).
Please provide link or errors

**Comment by achmadtunggulaji** [comment]
thanks for reply,

but sorry i am working offline, i already change it on custom_image_and_upload_wysihtml5.js, thanks for all support, i will post here when i can fix that error, maybe i should check jqueryupload.js too
